CREATE TABLE IF NOT EXISTS zv (
    deal_count int,          -- Darījumu skaits atlasē Number (10)
    deal_id int,             -- Darījuma ID Number (10)
    cadastr_nr int,          -- Īpašuma kadastra numurs Number (11)
    address varchar(256),    -- Adreses pieraksts Varchar2 (256 byte)
    county varchar(256),     -- Novads Varchar2 (256 byte)
    city varchar(256),       -- Pilsēta Varchar2 (256 byte)
    parish varchar(256),     -- Pagasts Varchar2 (256 byte)
    column_8 int,            -- NĪLM (lielākais pēc platības) Number (10)
    column_9 varchar(256),   -- NĪLM kodi(saraksts) Varchar2 (256 byte)
    deal_date DATE,          -- Darījuma datums Date (dd.mm.yyyy)
    deal_amount numeric,     -- Darījuma summa, EUR Number (18,6)
    column_12 int,           -- Zemes vienību skaits Number (5)
    column_13 int,           -- Zemes vienību kadastra apzīmējumu saraksts (vienadarījuma ietvaros) Varchar2 (4000byte)
    column_14 boolean,       -- Vai zeme ir apbūvēta (0-nav/1-ir) Number (1)
    column_15 numeric,       -- Pārdotā zemes kopplatība, m2 Number (12,2)
    column_16 numeric,       -- Pārdotā lauksaimniecības zemes platība, m2 Number (12,2)
    column_17 numeric,       -- Pārdotā aramzemes platība, m2 Number (12,2)
    column_18 numeric,       -- Pārdotā augļu dārzu platība, m2 Number (12,2)
    column_19 numeric,       -- Pārdotā pļavu platība, m2 Number (12,2)
    column_20 numeric,       -- Pārdotā ganību platība, m2 Number (12,2)
    column_21 numeric,       -- Pārdotā meliorētās LIZ platība, m2 Number (12,2)
    column_22 numeric,       -- Pārdotā mežu zemes platība, m2 Number (12,2)
    column_23 numeric,       -- Pārdotā krūmāju platība, m2 Number (12,2)
    column_24 numeric,       -- Pārdotā purvu platība, m2 Number (12,2)
    column_25 numeric,       -- Pārdotā zemes zem ūdeņiem platība, m2 Number (12,2)
    column_26 numeric,       -- Pārdotā zemes zem dīķiem platība, m2 Number (12,2)
    column_27 numeric,       -- Pārdotā zemes zem ēkām un pagalmiem platība, m2 Number (12,2)
    column_28 numeric,       -- Pārdotā zemes zem ceļiem platība, m2 Number (12,2)
    column_29 numeric,       -- Pārdotā pārējās zemes platība, m2 Number (12,2)
    column_30 int,           -- Zemes daļas (skaitītājs) Number (10)
    column_31 int            -- Zemes daļas (saucējs) Number (10)
);

CREATE TABLE IF NOT EXISTS zvb (
    deal_count int,                   -- Darījumu skaits atlasē Number (10)
    deal_id int,                      -- Darījuma ID Number (10)
    obejct varchar(256),              -- Objekts Varchar2 (256 byte)
    cadastr_nr int,                   -- Īpašuma kadastra numurs Number (11)
    address varchar(256),             -- Adreses pieraksts Varchar2 (256 byte)
    county varchar(256),              -- Novads Varchar2 (256 byte)
    city varchar(256),                -- Pilsēta Varchar2 (256 byte)
    parish varchar(256),              -- Pagasts Varchar2 (256 byte)
    column_09 int,                    -- NĪLM (lielākais pēc platības) Number (10)
    column_01 varchar(256),           -- NĪLM kodi(saraksts) Varchar2 (256 byte)
    deal_date DATE,                   -- Darījuma datums Date (dd.mm.yyyy)
    deal_amount numeric,              -- Darījuma summa, EUR Number (18,6)
    column_12 int,                    -- Zemes vienību skaits Number (5)
    column_13 varchar(4000),          -- Zemes vienību kadastra apzīmējumu saraksts (viena darījuma ietvaros) Varchar2 (4000 byte)
    column_14 int,                    -- Zemes daļas (skaitītājs) Number (10)
    column_15 int,                    -- Zemes daļas (saucējs) Number (10)
    column_16 numeric,                -- Pārdotā zemes kopplatība, m2 Number (12,2)
    column_17 numeric,                -- Pārdotā lauksaimniecības zemes platība, m2 Number (12,2)
    column_18 numeric,                -- Pārdotā aramzemes platība, m2 Number (12,2)
    column_19 numeric,                -- Pārdotā augļu dārzu platība, m2 Number (12,2)
    column_20 numeric,                -- Pārdotā pļavu platība, m2 Number (12,2)
    column_21 numeric,                -- Pārdotā ganību platība, m2 Number (12,2)
    column_22 numeric,                -- Pārdotā meliorētās LIZ platība, m2 Number (12,2)
    column_23 numeric,                -- Pārdotā mežu zemes platība, m2 Number (12,2)
    column_24 numeric,                -- Pārdotā krūmāju platība, m2 Number (12,2)
    column_25 numeric,                -- Pārdotā purvu platība, m2 Number (12,2)
    column_26 numeric,                -- Pārdotā zemes zem ūdeņiem platība, m2 Number (12,2)
    column_27 numeric,                -- Pārdotā zemes zem dīķiem platība, m2 Number (12,2)
    column_28 numeric,                -- Pārdotā zemes zem ēkām un pagalmiem platība, m2 Number (12,2)
    column_29 numeric,                -- Pārdotā zemes zem ceļiem platība, m2 Number (12,2)
    column_30 numeric,                -- Pārdotā pārējās zemes platība, m2 Number (12,2)
    column_31 int,                    -- Būvju skaits Number (10)
    column_32 int,                    -- Būves kadastra apzīmējums Number (17)
    column_33 int,                    -- Būves daļas, skaitītājs Number (12)
    column_34 int,                    -- Būves daļas, saucējs Number (12)
    column_35 varchar(256),           -- Būves lietošanas veida nosaukums Varchar2 (256 byte)
    column_36 int,                    -- Būves lietošanas veida kods Number (10)
    column_37 int,                    -- Būves virszemes stāvu skaits Number (5)
    column_38 numeric,                -- Būves apbūves laukums, m2 Number (12,2)
    column_39 numeric,                -- Būves kopplatība, m2 Number (12,2)
    column_40 numeric,                -- Būves būvtilpums, m3 Number (10,2)
    commissioning_year varchar(4000), -- Būves ekspluatācijas uzsākšanas gads Varchar2 (4000 byte)
    column_42 varchar(256),           -- Būves ārsienu materiāla nosaukums Varchar2 (256 byte)
    column_43 numeric                 -- Būves fiziskais nolietojums, % Number (5,2)
);


CREATE TABLE IF NOT EXISTS tg (
    deal_count int,                   -- Darījumu skaits atlasē Number (10)
    deal_id int,                      -- Darījuma ID Number (10)
    obejct varchar(256),              -- Objekts Varchar2 (256 byte)
    cadastr_nr int,                   -- Īpašuma kadastra numurs Number (11)
    address varchar(256),             -- Adreses pieraksts Varchar2 (256 byte)
    county varchar(256),              -- Novads Varchar2 (256 byte)
    city varchar(256),                -- Pilsēta Varchar2 (256 byte)
    parish varchar(256),              -- Pagasts Varchar2 (256 byte)
    deal_date DATE,                   -- Darījuma datums Date (dd.mm.yyyy)
    deal_amount numeric,              -- Darījuma summa, EUR Number (18,6)
    column_11 varchar(4000),          -- Zemes vienību kadastra apzīmējumi(saraksts) (viena darījuma ietvaros) Varchar2 (4000 byte)
    column_12 int,                    -- Zemes daļas(skaitītājs) Number (10)
    column_13 int,                    -- Zemes daļas(saucējs) Number (10)
    column_14 numeric,                -- Pārdotā zemes kopplatība, m2 Number (12,2)
    column_15 int,                    -- NĪLM grupas kods (lielākais pēc platības) Number (10)
    column_16 varchar(256),           -- NĪLM kodi(saraksts) Varchar2 (256 byte)
    column_17 int,                    -- Būvju skaits Number (10)
    column_18 int,                    -- Būves kadastra apzīmējums Number (17)
    column_19 int,                    -- Būves daļas(skaitītājs) Number (12)
    column_20 int,                    -- Būves daļas(saucējs) Number (12)
    column_21 varchar(256),           -- Būves lietošanas veida nosaukums Varchar2 (256 byte)
    column_22 int,                    -- Būves lietošanas veida kods Number (10)
    column_23 int,                    -- Būves virszemes stāvu skaits Number (5)
    column_24 numeric,                -- Būves apbūves laukums, m2 Number (12,2)
    column_25 numeric,                -- Būves kopplatība, m2 Number (12,2)
    column_26 numeric,                -- Būves būvtilpums, m3 Number (10,2)
    column_27 varchar(256),           -- Būves ārsienu materiāla nosaukums Varchar2 (256 byte)
    commissioning_year varchar(4000), -- Būves ekspluatācijas uzsākšanas gads Varchar2 (4000 byte)
    column_29 numeric,                -- Būves fiziskais nolietojums, % Number (5,2)
    column_30 varchar(4000),          -- Būves kadastra apzīmējumu saraksts (viena darījuma ietvaros) Varchar2 (4000 byte)
    column_31 int,                    -- Telpu grupu skaits (viena darījuma ietvaros) Number (5)
    column_32 int,                    -- Dzīvokļu skaits (viena darījuma ietvaros) Number (5)
    column_33 int,                    -- Telpu grupas kadastra apzīmējums Number (17)
    column_34 int,                    -- Telpu grupas daļas(skaitītājs) Number (12)
    column_35 int,                    -- Telpu grupas daļas(saucējs) Number (12)
    column_36 int,                    -- Telpu grupas lietošanas veida kods Number (10)
    column_37 int,                    -- Telpu grupas zemākais stāvs Number (5)
    column_38 int,                    -- Telpu grupas augstākais stāvs Number (5)
    column_39 numeric,                -- Telpu grupas platība, m2 Number (12,2)
    column_40 numeric,                -- Dzīvokļa kopplatība, m2 Number (12,2)
    column_41 int,                    -- Telpu skaits telpu grupā Number (5)
    column_42 int                     -- Istabu skaits dzīvoklī Number (5)
);